spring.application.name=rabbitmq-demo

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.name=myat_thukha
rabbitmq.jason.queue.name=myat_thukha_json
rabbitmq.routing_key.name=mtk_routing_key
rabbitmq.json.routing_key.name=mtk_json_routing_key
rabbitmq.exchange.name=mtk_exchange
